# Generated by Django 3.1.7 on 2021-03-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://www.peregrinoteca.com/uploads/media/images/396x396/xzapatillas-salomon-xa-pro-3d-gtx-w-rojo-coral-negro-1.jpg.pagespeed.ic.0gp9Li60lz.webp', max_length=150, verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
